### ISSUE TITLE
Adding New Sections

### ISSUE THREAD

**Issue by dragonstar41** [dragonstar41/My-Portfolio#1]
The issue for ideating and adding new sections.

New Sections
Video
Podcast
Tweets
Achievements
Let us discuss these sections and start adding these sections to make it even better!

Please do suggest any new sections which we can add as well here!

**Comment by topcoder20022** [comment]
OK, I will email you to discuss in more deails.
Thanks.

**Comment by dragonstar41** [comment]
My Email is upworkstar@gmail.com
You can find me in skype, telegram, discord, slack as well.
Thanks.
